import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";

const inter = Inter({
    display: "swap",
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = await auth();

    console.log(session);

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      <SessionProvider session={session}>
        {children}
        </SessionProvider>
      <Toaster />
      </body>
    </html>
  );
}
